{
 "title": "Running Services",
 "time": { "from": "now", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   { "name": "service_name", "query": "process_resident_memory_bytes" }
  ]
 },
 "panels": [
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "repeat": "service_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "$service_name instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(process_resident_memory_bytes{job=\"$service_name\"})",
     "legendFormat": "$service_name  Instances"
    }
   ]
  },
  {
   "title": "Pending Crop Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(crop_tasks_pending)" }
   ]
  },
  {
   "title": "Pending Most Significant Image Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(most_significant_image_tasks_pending)"
    }
   ]
  },
  {
   "title": "Portrait Crop Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(portrait_tasks_pending)" }
   ]
  },
  {
   "title": "Pending Optimization Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(optimization_tasks_pending)"
    }
   ]
  },
  {
   "title": "Pending Crop Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(screenshot_tasks_pending)" }
   ]
  }
 ]
}