version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    volumes:
      - ${PWD}/imgs:/data
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
