{
 "title": "Running Services",
 "time": { "from": "now", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, namespace)"
   },
   { "name": "service_name", "query": "process_resident_memory_bytes" }
  ]
 },
 "panels": [
  {
   "title": "Pending Crop Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(crop_tasks_pending)" }
   ]
  },
  {
   "title": "Pending Most Significant Image Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(most_significant_image_tasks_pending)"
    }
   ]
  },
  {
   "title": "Portrait Crop Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(portrait_tasks_pending)" }
   ]
  },
  {
   "title": "Pending Optimization Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(optimization_tasks_pending)"
    }
   ]
  },
  {
   "title": "Pending Portrait Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(portrait_tasks_pending)" }
   ]
  },
  {
   "title": "Crop Service Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"crop_service\"})"
    }
   ]
  },
  {
   "title": "MostSignificant Service Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"most_significant_image_service\"})"
    }
   ]
  },
  {
   "title": "Optimization Service Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"optimization_service\"})"
    }
   ]
  },
  {
   "title": "Screenshot Service Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"screenshot_service\"})"
    }
   ]
  },
  {
   "title": "Portrait Service Instances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(up{job=\"portrait_service\"})"
    }
   ]
  }
 ]
}