version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    volumes:
      - ${PWD}/imgs:/data
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    volumes:
      - ${PWD}/infrastructure/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/infrastructure/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure

  gateway:
    image: swarm_gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
    deploy:
      restart_policy:
        condition: on-failure
