version: '3'
services:
  faktory:
    image: contribsys/faktory
    ports:
      - "7419:7419"
      - "7420:7420"
    deploy:
      restart_policy:
        condition: on-failure

  crop:
    image: kit_crop
    env_file:
      - .env
    depends_on:
      - "faktory"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 350M
      restart_policy:
        condition: on-failure
