groups:
  - name: default
    rules:
      - alert: ManyCropTasksPending
        expr: sum(crop_tasks_pending) > 100
        labels:
          severity: critical
      - alert: TooManyCropInstances
        expr: sum(crop_tasks_pending) < 100
          labels:
            severity: critical
      - alert: MostSignificantImageTasksPending
          expr: sum(most_significant_image_tasks_pending) > 100
          labels:
            severity: critical
      - alert: TooMostSignificantImageInstances
        expr: sum(most_significant_image_tasks_pending) < 100
          labels:
            severity: critical
      - alert: ManyOptimizationTasksPending
          expr: sum(optimization_tasks_pending) > 100
          labels:
            severity: critical
      - alert: TooManyOptimizationInstances
        expr: sum(optimization_tasks_pending) < 100
          labels:
            severity: critical
      - alert: ManyScreenshotTasksPending
          expr: sum(screenshot_tasks_pending) > 100
          labels:
            severity: critical
      - alert: TooManyScreenshotInstances
        expr: sum(screenshot_tasks_pending) < 100
          labels:
            severity: critical


