version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    command: server /data
    env_file: .env

  faktory:
    image: contribsys/faktory:0.9.1
    ports:
      - "7419:7419"
      - "7420:7420"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"