version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    command: server /data
    env_file: .env

  faktory:
    image: contribsys/faktory:0.9.1
    ports:
      - "7419:7419"
      - "7420:7420"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  crop:
    build:
      context: src/service/crop
    ports:
      - "8081:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"

  most_significant_image:
    build:
      context: src/service/most_significant_image
    ports:
      - "8082:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"

  optimization:
    build:
      context: src/service/optimization
    ports:
      - "8083:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"

  portrait:
    build:
      context: src/service/portrait
    ports:
      - "8084:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"

  screenshot:
    build:
      context: src/service/screenshot
    ports:
      - "8085:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"


