version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    command: server /data
    env_file: .env

  faktory:
    image: contribsys/faktory:0.9.1
    ports:
      - "7419:7419"
      - "7420:7420"

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=simple_ms
    env_file: .env

  request_service:
    build:
      context: src/request_service
    depends_on:
    - "postgres"

  gateway:
    build:
      context: gateway
    ports:
      - "8080:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"

  crop:
    build:
      context: src/service/crop
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"

  most_significant_image:
    build:
      context: src/service/most_significant_image
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"

  optimization:
    build:
      context: src/service/optimization
    env_file: .env
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"

  portrait:
    build:
      context: src/service/portrait
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"

  screenshot:
    build:
      context: src/service/screenshot
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
