version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    command: server /data
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure

  faktory:
    image: contribsys/faktory:0.9.1
    ports:
      - "7419:7419"
      - "7420:7420"
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    volumes:
      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=simple_ms
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure

  request_service:
    image: swarm_request_service
    depends_on:
    - "postgres"
    deploy:
      restart_policy:
        condition: on-failure

  gateway:
    image: swarm_gateway
    ports:
      - "8080:8080"
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      restart_policy:
        condition: on-failure

  crop:
    image: swarm_crop
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

  most_significant_image:
    image: swarm_most_significant_image
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

  optimization:
    image: swarm_optimization
    env_file: .env
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

  portrait:
    image: swarm_portrait
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

  screenshot:
    image: swarm_screenshot
    depends_on:
      - "minio"
      - "faktory"
      - "prometheus"
      - "request_service"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure
