version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    command: server /data
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure

  faktory:
    image: contribsys/faktory:0.9.1
    ports:
      - "7419:7419"
      - "7420:7420"
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"
    deploy:
      restart_policy:
        condition: on-failure

#  grafana:
#    image: grafana/grafana
#    volumes:
#      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
#      - ${PWD}/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
#      - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards/
#    ports:
#      - "3000:3000"
#    deploy:
#      restart_policy:
#        condition: on-failure
