version: '3'
services:

  minio:
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    volumes:
      - ${PWD}/imgs:/data
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure

  faktory:
    image: contribsys/faktory
    ports:
      - "7419:7419"
      - "7420:7420"
    deploy:
      restart_policy:
        condition: on-failure

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ${PWD}/infrastructure/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - "scale-service"
    deploy:
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    volumes:
      - ${PWD}/infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/infrastructure/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    depends_on:
      - "alertmanager"
    deploy:
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    volumes:
      - ${PWD}/infrastructure/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/infrastructure/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PWD}/infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure

