groups:
  - name: default
    rules:
      - alert: ManyCropTasksPending
        expr: sum(up{job="crop_service"}) * 10 < sum(crop_tasks_pending) + 1
        labels:
          severity: critical
          tasks: sum(crop_task_pending)
      - alert: TooManyCropInstances
        expr: sum(up{job="crop_service"}) * 5 > sum(crop_tasks_pending) + 5
        labels:
          severity: critical
      - alert: ManyMostSignificantImageTasksPending
        expr: sum(up{job="most_significant_iamge_service"}) * 10 < sum(most_significant_image_tasks_pending) + 1
        labels:
          severity: critical
      - alert: TooMostSignificantImageInstances
        expr: sum(up{job="most_significant_iamge_service"}) * 5 > sum(most_significant_image_tasks_pending) + 5
        labels:
          severity: critical
      - alert: ManyOptimizationTasksPending
        expr: sum(up{job="optimization_service"}) * 10 < sum(optimization_tasks_pending) + 1
        labels:
          severity: critical
      - alert: TooManyOptimizationInstances
        expr: sum(up{job="optimization_service"}) * 5 > sum(optimization_tasks_pending) + 5
        labels:
          severity: critical
      - alert: ManyScreenshotTasksPending
        expr: sum(up{job="screenshot_service"}) * 10 < sum(screenshot_tasks_pending) + 1
        labels:
          severity: critical
      - alert: TooManyScreenshotInstances
        expr: sum(up{job="screenshot_service"}) * 5 > sum(screenshot_tasks_pending) + 5
        labels:
          severity: critical


